# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Require password encryption from all Unix domain socket connections
local    all            all                                     scram-sha-256
# Require password encryption for all ssl connections
hostssl  all            all             all                     scram-sha-256
# Reject all non-ssl connections
host     all            all             all                     reject
