name: production

volumes:
  cxgndata:
  npmdata:

services:
  breedbase_db:
    extends:
      file: docker/breedbase/db.yml
      service: breedbase_db
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}          # Create 'postgres' superuser with this password
      PGPASSWORD:        ${PGPASSWORD}          # Default psql connection password
      WEB_USR_PASSWORD:  ${WEB_USR_PASSWORD}    # Database password for 'web_usr'

  breedbase:
    extends:
      file: docker/breedbase/web.yml
      service: breedbase
    environment:
      MODE:              PRODUCTION             # SGN Server Mode
      PGDATABASE:        ${PGDATABASE:?}        # Database name
      PGPASSWORD:        ${PGPASSWORD:?}        # Database password for 'postgres' superuser
      WEB_USR_PASSWORD:  ${WEB_USR_PASSWORD:?}  # Database password for 'web_usr'
      ADMIN_PASSWORD:    ${ADMIN_PASSWORD:?}    # Breedbase web password for admin user
    volumes:
      - cxgndata:/home/production/cxgn
      - npmdata:/home/production/npm

  caddy:
    extends:
      file: docker/caddy/caddy.yml
      service: caddy
    volumes:
      - cxgndata:/home/production/cxgn
