name: quickstart

include:
  - docker/breedbase/db.yml          # Breedbase Database

volumes:
  npmdata:

services:
  breedbase:
    extends:
      file: docker/breedbase/web.yml
      service: breedbase
    volumes:
      - npmdata:/home/production/npm
