services:

  # Add: Create a keycloak user and db
  breedbase_db:
    environment:
      KEYCLOAK_PASSWORD: keycloak
      POSTGRES_PASSWORD: password
      PGPASSWORD:        password
      WEB_USR_PASSWORD:  password

    healthcheck:
      test: [ "CMD-SHELL", "psql -U postgres -q keycloak -c '\\dt'"]
      interval: 5s
      timeout: 5s
      retries: 30

  # Add build instructions, also depends on keycloak
  # add development volumes
  breedbase:
    build:
      context: .
      cache_from:
        - bffafirms/breedbase:latest
    depends_on:
      keycloak:
        condition: service_healthy              
    volumes:
      - ./cxgn:/home/production/cxgn
      - ./entrypoint.sh:/entrypoint.sh
        # include .git dir that tracks all submodules in cxgn
      - ./.git:/home/production/.git
    environment:
      MODE:                   DEVELOPMENT
      HOME:                   /home/sgn
      SGN_TEST_SERVER:        http://breedbase:3010
      SGN_REMOTE_SERVER_ADDR: selenium
      DBIC_TRACE:             0
      # Simplified passwords for local development
      PGPASSWORD:             password
      WEB_USR_PASSWORD:       password
      ADMIN_PASSWORD:         password
