volumes:
  staticdata:
  jsdata:

services:
  breedbase_db:
    extends:
      file: docker/db.yml
      service: db
    hostname: breedbase_db
    container_name: breedbase_db
    environment:
      WEB_USR_PASSWORD: web_usr
      TLS_DOMAIN: breedbase_db
  
  breedbase:
    extends:
      file: docker/web.yml
      service: breedbase
    volumes:
      - type: bind
        source: ./docker/web_entrypoint.sh
        target: /entrypoint.sh
        bind:
          create_host_path: false

      # TMP: web_setup script
      - type: bind
        source: ./docker/web_setup
        target: /usr/local/bin/web_setup
        bind:
          create_host_path: false
