# modifications to existing services
include:
   - path:
       - docker-compose.yml
       - development.yml

# New services
services:

  keycloak:
    hostname: keycloak
    container_name: keycloak
    build:
      context: cxgn/sgn/.github/keycloak
    image: bffafirms/keycloak:26.5.1-0-breedbase-testing
    # Restrict security privileges
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL
    depends_on:
      breedbase_db:
        condition: service_healthy
    environment:
      KC_DB_USERNAME:              postgres
      KC_DB_PASSWORD:              postgres
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
    ports:
      - "9080:9080"
