volumes:
  staticdata:
  jsdata:

services:

  # ---------------------------------------------------------------------------
  # App: Breedbase/Solgenomics (SGN) Frontend and Backend

  breedbase:
    hostname: breedbase
    image: bffafirms/breedbase:latest
    restart: unless-stopped
    depends_on:
      breedbase_db:
        condition: service_healthy
    tty: true
    # Note: container will start as root, and then switch to run as the
    # the USER_GROUP_ID user.
    environment:
      USER_GROUP_ID:            ${USER_GROUP_ID:?}
      DOMAIN_NAME:              ${DOMAIN_NAME:-localhost}
      MODE:                     PRODUCTION
      # Database credentials
      PGHOST:                   breedbase_db
      PGSSLROOTCERT:            /data/certs/root.crt
      PGSSLMODE:                verify-full
      PGDATABASE:               ${PGDATABASE:?}
      PGUSER:                   ${PGUSER:?}
      PSQL_PAGER:               cat
      PGPASSWORD:               ${PGPASSWORD:?}
      HISTTIMEFORMAT:           "%Y-%m-%d %T "
      HOME:                     /home/production
      WEB_USR_PASSWORD:         ${WEB_USR_PASSWORD:?} # web_usr database password
      ADMIN_PASSWORD:           ${ADMIN_PASSWORD:?}   # admin web password
    volumes:
      # required volumes
      - ./db_dumps:/db_dumps:ro                                      # Default fixture for PRODUCTION mode
      - ./data/breedbase:/home/production/volume                     # Breedbase web data
      - ./data/postgres/certs/root.crt:/data/certs/root.crt:ro       # SSL Certificates for database communication
      - ./data/breedbase/sgn_local.conf:/home/production/cxgn/sgn/sgn_local.conf:ro # Config
      - ./data/breedbase/starmachine.conf:/etc/starmachine/starmachine.conf:ro # Starmachine server
      # recommended volumes for persistence and quick start up 
      - ./data/breedbase/bash_history:/home/production/.bash_history # Keep history of commands
      - staticdata:/home/production/cxgn/sgn/static                  # Static files
      - jsdata:/home/production/cxgn/js/static                       # Unknown
      - ./data/downloads:/downloads
      # dev
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./run_all_patches.pl:/home/production/cxgn/sgn/db/run_all_patches.pl:ro
    expose:
      - 8080
    ports: ["8080:8080"]
    healthcheck:
      test: curl -I localhost:8080
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 8G
        reservations:
          cpus: 1
          memory: 1G

  # ---------------------------------------------------------------------------
  # Database

  breedbase_db:
    hostname: breedbase_db
    build:
      context: postgres
    image: bffafirms/postgres:latest
    restart: unless-stopped
    # Restrict security privileges
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL
    # Run as the host user, so that when we mount the database files
    # to a local path, they are also owned by the host user
    user: ${USER_GROUP_ID}
    environment:
      TLS_DOMAIN:          breedbase_db           # Domain name for TLS certficates
      USER_GROUP_ID:       ${USER_GROUP_ID:?}     # Ensure we have information about the host user
      PGDATA:              /data/postgresql/main  # Install the database in a custom folder for non-root access
      POSTGRES_USER:       postgres               # Postgres Superuser
      POSTGRES_PASSWORD:   ${PGPASSWORD:?}        # Postgres Superuser
      PGUSER:              postgres               # Default connection user
      PGPASSWORD:          ${PGPASSWORD:?}        # Default connection password
      TZ:                  'America/Edmonton'     # Container timezone
      # Applications
      WEB_USR_PASSWORD:    ${WEB_USR_PASSWORD:?}  # web_usr database password
    volumes:
      # required volumes
      - ./data/postgres/db:/data/postgresql          # Postgres database files
      - ./data/postgres/pgbackrest:/data/pgbackrest  # Database backups
      - ./data/postgres/certs:/data/certs            # TLS certificates (self-signed)
      - ./data/postgres/log:/data/log                # Log Files
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro # Custom authentication
    expose:
      - "5432"
    healthcheck:
      # Check that the final database has been created
      test: [ "CMD-SHELL", "psql -U postgres -q web_usr -c '\\dt'"]
      interval: 5s
      timeout: 5s
      retries: 30
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 16G
        reservations:
          cpus: 2
          memory: 4G
