volumes:
  staticdata:
  jsdata:

services:

  breedbase_db:
    extends:
      file: docker/db.yml
      service: db
    hostname: breedbase_db
    container_name: breedbase_db
    environment:
      WEB_USR_PASSWORD: postgres
      TLS_DOMAIN: breedbase_db
    healthcheck:
      test: [ "CMD-SHELL", "psql -U postgres -q web_usr -c '\\dt'"]

  keycloak_db:
    container_name: keycloak_db
    hostname: keycloak_db
    extends:
      file: docker/keycloak_db.yml
      service: keycloak_db

  keycloak:
    extends:
      file: docker/keycloak.yml
      service: keycloak
    depends_on:
      keycloak_db:
        condition: service_healthy

  novnc:
    extends:
      file: docker/novnc.yml
      service: novnc

  selenium:
    extends:
      file: docker/selenium.yml
      service: selenium
    depends_on:
      novnc:
        condition: service_started

  test_breedbase:
    container_name: test_breedbase
    hostname: test_breedbase
    extends:
      file: docker/web.yml
      service: breedbase
    restart: on-failure:3
    depends_on:
      breedbase_db:
        condition: service_healthy    
      keycloak:
        condition: service_healthy          
    environment:
      MODE:                   TESTING
      SGN_TEST_SERVER:        http://test_breedbase:3010
    command: ["--interactive"]
    ports:
      - 3010:3010
    healthcheck:
      test: curl -I localhost:3010   
    volumes:
      # required volumes
      - type: bind
        source: ./cxgn
        target: /home/production/cxgn
        bind:
          create_host_path: false

        # include .git dir that tracks all submodules in cxgn
      - type: bind
        source: ./.git
        target: /home/production/.git
        bind:
          create_host_path: false
