volumes:
  staticdata:
  jsdata:

services:

  breedbase_db:
    extends:
      file: docker/db.yml
      service: db
    hostname: breedbase_db
    container_name: breedbase_db
    environment:
      WEB_USR_PASSWORD: web_usr
      TLS_DOMAIN: breedbase_db

  keycloak_db:
    container_name: keycloak_db
    hostname: keycloak_db
    extends:
      file: docker/db.yml
      service: db
    environment:
      KEYCLOAK_PASSWORD: keycloak
      TLS_DOMAIN: keycloak_db
    healthcheck:
      test: [ "CMD-SHELL", "psql -U postgres -q keycloak -c '\\dt'"]
    volumes: !overrides
      - type: bind
        source: ./data/keycloak_db/db
        target: /data/postgresql
        bind:
          create_host_path: false

      - type: bind
        source: ./data/keycloak_db/pgbackrest
        target: /data/pgbackrest
        bind:
          create_host_path: false

      - type: bind
        source: ./data/keycloak_db/certs
        target: /data/certs
        bind:
          create_host_path: false

      - type: bind
        source: ./data/keycloak_db/log
        target: /data/log
        bind:
          create_host_path: false

  keycloak:
    extends:
      file: docker/keycloak.yml
      service: keycloak
    depends_on:
      keycloak_db:
        condition: service_healthy

  breedbase:
    extends:
      file: docker/web.yml
      service: breedbase
    depends_on:
      breedbase_db:
        condition: service_healthy    
      keycloak:
        condition: service_healthy          
    environment:
      MODE:                   DEVELOPMENT
      HOME:                   /home/sgn
      SGN_TEST_SERVER:        http://breedbase:3010
      SGN_REMOTE_SERVER_ADDR: selenium
      DBIC_TRACE:             0
    volumes:
      # required volumes
      - type: bind
        source: ./cxgn
        target: /home/production/cxgn
        bind:
          create_host_path: false

        # include .git dir that tracks all submodules in cxgn
      - type: bind
        source: ./.git
        target: /home/production/.git
        bind:
          create_host_path: false
