volumes:
  staticdata:
  jsdata:

services:
  breedbase_db:
    extends:
      file: docker/db.yml
      service: db
    hostname: breedbase_db
    container_name: breedbase_db
    environment:
      TLS_DOMAIN:        breedbase_db           # Domain name for TLS certficates
      USER_GROUP_ID:     ${USER_GROUP_ID:?}     # Ensure we have information about the host user
      POSTGRES_PASSWORD: ${PGPASSWORD}          # Createt Postgres Superuser password
      PGPASSWORD:        ${PGPASSWORD}          # Default connection password
      WEB_USR_PASSWORD:  ${WEB_USR_PASSWORD}    # Web User Password
    healthcheck:
      test: [ "CMD-SHELL", "psql -U postgres -q web_usr -c '\\dt'"]
  
  breedbase:
    extends:
      file: docker/web.yml
      service: breedbase
    environment:
      MODE:              PRODUCTION             # SGN Server Mode
      PGDATABASE:        ${PGDATABASE:?}        # Database name
      PGPASSWORD:        ${PGPASSWORD:?}        # Password for postgres superuser
      WEB_USR_PASSWORD:  ${WEB_USR_PASSWORD:?}  # Password for web_usr
      ADMIN_PASSWORD:    ${ADMIN_PASSWORD:?}    # Web Password for admin user

  caddy:
    extends:
      file: docker/caddy.yml
      service: caddy