volumes:
  staticdata:
  jsdata:

services:
  breedbase_db:
    extends:
      file: docker/db.yml
      service: db
    hostname: breedbase_db
    container_name: breedbase_db
    environment:
      WEB_USR_PASSWORD: postgres
      TLS_DOMAIN: breedbase_db
    healthcheck:
      test: [ "CMD-SHELL", "psql -U postgres -q web_usr -c '\\dt'"]
  
  breedbase:
    extends:
      file: docker/web.yml
      service: breedbase
