volumes:
  staticdata:
  jsdata:

services:
  breedbase_db:
    extends:
      file: docker/db.yml
      service: db
    hostname: breedbase_db
    container_name: breedbase_db
    environment:
      WEB_USR_PASSWORD: web_usr
      TLS_DOMAIN: breedbase_db
  
  breedbase:
    extends:
      file: docker/web.yml
      service: breedbase
