volumes:
  staticdata:
  jsdata:

services:
  breedbase:
    restart: always
    environment:
      MODE: 'PRODUCTION'
      PGDATABASE: ${PGDATABASE:?}
      PGHOST: ${PGHOST:?}
      PGPASSWORD: ${PGPASSWORD:?}
      PGUSER: ${PGUSER:?}
    volumes:
      - ./db_dumps:/db_dumps
      - ./data/web:/home/production/volume
      - staticdata:/home/production/cxgn/sgn/static
      - jsdata:/home/proudction/cxgn/js/static

  breedbase_db:
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD:?}
    volumes:
      - ./data/db:/var/lib/postgresql/data
