services:
  breedbase:
    restart: always
    environment:
      MODE: 'PRODUCTION'
      PGDATABASE: ${PGDATABASE:?}
      PGHOST: ${PGHOST:?}
      PGPASSWORD: ${PGPASSWORD:?}
      PGUSER: ${PGUSER:?}
    volumes:
      - ./db_dumps:/db_dumps

  breedbase_db:
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD:?}
