#!/bin/bash

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
NC="\e[0m" # No Color

echo -e "-----------------------------------------------------------------------------"
echo -e "$(date '+%Y-%m-%d %H:%m:%S')\tBeginning setup."

echo -e "$(date '+%Y-%m-%d %H:%m:%S')\tGenerating secure credentials: .env"

if [[ ! -e .env ]]; then
    {
        echo USER_GROUP_ID=$(id -u):$(id -g)
        echo DOMAIN_NAME=localhost
        echo SITE_BASE=bff-afirms
        echo PGHOST=breedbase_db
        echo PGDATABASE=breedbase
        echo PGUSER=postgres
        echo PGPASSWORD=$(cat /dev/urandom | LC_CTYPE=C tr -dc 'a-zA-Z0-9' | head -c 50)
        echo ADMIN_PASSWORD=$(cat /dev/urandom | LC_CTYPE=C tr -dc 'a-zA-Z0-9' | head -c 50)
        echo WEB_USR_PASSWORD=$(cat /dev/urandom | LC_CTYPE=C tr -dc 'a-zA-Z0-9' | head -c 50)
        echo SECRET_KEY=$(cat /dev/urandom | LC_CTYPE=C tr -dc 'a-zA-Z0-9' | head -c 32)
    } > .env
fi
source .env
USER_ID=$(echo $USER_GROUP_ID | cut -d ":" -f 1)
GROUP_ID=$(echo $USER_GROUP_ID | cut -d ":" -f 2)

if [[ ! -e .env.bak ]]; then
    cp .env .env.bak
fi

echo -e "$(date '+%Y-%m-%d %H:%m:%S')\tCreating data directories: data/"

mkdir -p data/
cd data

# Postgres Databases
for db in breedbase_db keycloak_db; do
  mkdir -p $db
  cd $db
  mkdir -p certs db log pgbackrest/archive pgbackrest/backup pgbackrest/log spool
  cd ../
done

# breedbase
mkdir -p breedbase/volume breedbase/downloads
touch breedbase/bash_history

if [[ ! -e breedbase/sgn_local.conf ]]; then

  sed \
    -e "s/{PROJECT_NAME}/$PROJECT_NAME/g" \
    -e "s/{DOMAIN_NAME}/$DOMAIN_NAME/g" \
    -e "s/{WEB_USR_PASSWORD}/$WEB_USR_PASSWORD/g" \
    -e "s/{BREEDBASE_CLIENT_SECRET}/$BREEDBASE_CLIENT_SECRET/g" \
    ../cxgn/bff-afirms/sgn_local_template.conf > breedbase/sgn_local.conf
fi

# keycloak web
mkdir -p keycloak/export

# caddy
mkdir -p caddy/log

# JbrowseGenome Browser
if [[ ! -d jbrowse ]]; then
  echo -e "$(date '+%Y-%m-%d %H:%m:%S')\tDownloading jbrowse files: jbrowse"

  if [[ ! -d jbrowse/app ]]; then
    mkdir -p jbrowse/app

    cd jbrowse/app
    wget -q https://github.com/GMOD/jbrowse-components/releases/download/v4.1.15/jbrowse-web-v4.1.15.zip
    unzip -q jbrowse-web-v4.1.15.zip
    rm -f jbrowse-web-v4.1.15.zip

    if [[ ! -e config.json ]]; then
      sed "s/{DOMAIN_NAME}/${DOMAIN_NAME}/g" ../../../docker/jbrowse/config.template.json > config.json
    fi

    cd ../../
  fi

  if [[ ! -d jbrowse/data ]]; then
    mkdir -p jbrowse/data
    cp -r ../docker/jbrowse/*demo jbrowse/data/
  fi
fi

echo -e "$(date '+%Y-%m-%d %H:%m:%S')\tCompleted setup."
echo -e "-----------------------------------------------------------------------------"
