# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Unix domain socket connection by any user, require password encruption
local    all            all                                     scram-sha-256
# Remote connections by super-user from breedbase, allow
hostssl  postgres       postgres        0.0.0.0/0               scram-sha-256
hostssl  breedbase      postgres        0.0.0.0/0               scram-sha-256
# Remote connections by super-user, reject
host     all            postgres        0.0.0.0/0               reject
hostssl  all            postgres        0.0.0.0/0               reject
# Remote connection, require password encryption and ssl
hostssl  all            all             all                     scram-sha-256