services:

  breedbase_db:
    hostname: breedbase_db
    extends:
      file: ../postgres/db.yml
      service: db
    environment:
      WEB_USR_PASSWORD: postgres
      TLS_DOMAIN:       breedbase_db
    healthcheck:
      test: [ "CMD-SHELL", "psql -U postgres -q web_usr -c '\\dt'"]
    volumes: !override

      - type: bind
        source: $PWD/data/breedbase_db/db
        target: /data/postgresql
        bind:
          create_host_path: false

      - type: bind
        source: $PWD/data/breedbase_db/pgbackrest
        target: /data/pgbackrest
        bind:
          create_host_path: false

      - type: bind
        source: $PWD/data/breedbase_db/certs
        target: /data/certs
        bind:
          create_host_path: false

      - type: bind
        source: $PWD/data/breedbase_db/log
        target: /data/log
        bind:
          create_host_path: false
