FROM quay.io/jupyter/base-notebook:x86_64-conda-26.7.1

# Switch to root to install packages
USER root

# System packages
RUN apt update -y \
  && apt upgrade -y \
  && apt install -y cmake g++ git gdebi-core gnupg pkg-config wget zlib1g-dev

# Conda packages
COPY conda.default.yml /home/root/environment.yml
RUN conda env update --file /home/root/environment.yml --name base

# RStudio Server
RUN wget https://download2.rstudio.org/server/jammy/amd64/rstudio-server-2026.08.2-200-amd64.deb \
  && gdebi -n rstudio-server-2026.08.2-200-amd64.deb \
  && rm -f rstudio-server-2026.08.2-200-amd64.deb

# Configure rstudio to recognize conda environment
COPY rstudio/rserver.conf /etc/rstudio/rserver.conf
COPY rstudio/rsession.sh /usr/lib/rstudio-server/bin/rsession.sh
COPY rstudio/profiles /etc/rstudio/profiles
COPY rstudio/Rprofile.site /opt/conda/lib/R/etc/Rprofile.site
RUN rstudio-server verify-installation

# Shiny Server
RUN wget https://download3.rstudio.org/ubuntu-20.04/x86_64/shiny-server-1.5.23.1030-amd64.deb \
  && gdebi -n shiny-server-1.5.23.1030-amd64.deb \
  && rm -f shiny-server-1.5.23.1030-amd64.deb

# VSCode Server
RUN curl -fOL https://github.com/coder/code-server/releases/download/v4.135.0/code-server_4.135.0_amd64.deb \
  && sudo dpkg -i code-server_4.135.0_amd64.deb \
  && rm -f code-server_4.135.0_amd64.deb

# Jupyter Kernels
RUN conda run python -m bash_kernel.install \
  && conda run Rscript -e 'IRkernel::installspec(name = "ir45", displayname = "R 4.5")'

# Create custom healthcheck
HEALTHCHECK --interval=10s --timeout=5s --retries=30 \
  CMD curl -f ${JUPYTERHUB_SERVICE_URL} || exit 1

# Create custom controlled user
RUN useradd -rm -s /bin/bash jupyter
USER jupyter

ENV JUPYTER_VSCODE_PROXY_USE_SOCKET=true
ENV RSTUDIO_CONDA_ENV=/opt/conda
