# Re-usable workflow to create the docker image
name: Docker

on:
  workflow_call:
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: bffafirms/breedbase

jobs:

  # ---------------------------------------------------------------------------
  image:

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Extract metadata (labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: bffafirms/breedbase:latest
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=tar,dest=breedbase.tar

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: breedbase-docker
          path: breedbase.tar
          retention-days: 1
          if-no-files-found: error