# Re-usable workflow to test deployments
name: Deployment

on:
  workflow_call:
    inputs:
      SITE_OVERLAY:
        required: false
        type: string
        default: sgn
  workflow_dispatch:
    inputs:
      SITE_OVERLAY:
        required: false
        type: string
        default: sgn
  schedule:
    - cron: '0 12 * * 0'

run-name: ${{ format('Deployment {0}', inputs.SITE_OVERLAY) }}

jobs:

  # ---------------------------------------------------------------------------
  # Deployment Modes

  deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      DOCKER_BUILDKIT: 1

    strategy:
      fail-fast: false
      matrix:
        include:
          - mode: quickstart
          - mode: development
          - mode: production
          - mode: testing

    steps:

      - name: Checkout breedbase_dockerfile repo
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Link compose file
        run: |
          ln -s compose.yml compose.quickstart.yml

      - name: Build container image
        run: docker build -t bffafirms/breedbase:latest .

      # ---------------------------------------------------------------------------
      # Deployments

      - name: Setup
        run: ./setup

      - name: Configure overlay
        run: sed -i -E "s/(SITE_OVERLAY=).*/\1${{ inputs.SITE_OVERLAY }}/g" .env

      - name: Start containers
        run: docker compose -f compose.${{ matrix.mode }}.yml up -d

      - name: Healthcheck containers
        uses: stringbean/docker-healthcheck-action@v3
        with:
          container: ${{ matrix.mode }}-breedbase-1
          wait-time: 300
          require-status: running
          require-healthy: true

      - name: DB container log
        if: always()
        run: docker compose -f compose.${{ matrix.mode }}.yml logs breedbase_db

      - name: Web container log
        if: always()
        run: docker compose -f compose.${{ matrix.mode }}.yml logs breedbase

      - name: Stop containers
        run: docker compose down

      - name: Clean volumes
        run: docker volume prune -af

      - name: Clean data
        run: rm -rf data
