name: Pull Request

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.png'
      - '.gitignore'

jobs:

  docker:
    uses: ./.github/workflows/docker.yml

  # lint:
  #   uses: ./.github/workflows/lint.yml

  # deployment:
  #   uses: ./.github/workflows/deployment.yml

  # test:
  #   uses: ./.github/workflows/test.yml
