# Re-usable workflow to test sgn site overlay
name: sgn

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 0'

jobs:
  deployment:
    uses: ./.github/workflows/deployment.yml
    with:
      SGN_BRANCH: master

  test:
    uses: ./.github/workflows/test.yml
    with:
      SGN_BRANCH: master
