# Re-usable workflow to run tests
name: Test

on:
  workflow_call:
    
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      RUN_TEST_CMD: docker compose -f docker-compose.testing.yml run --use-aliases test_breedbase -c
      PRUNE_CMD: docker container prune -f

    steps:

      - name: Checkout breedbase_dockerfile repo
        uses: actions/checkout@v6
        with:
          submodules: true
    
      - name: Build container image
        run: docker build -t bffafirms/breedbase:latest .

      # -----------------------------------------------------------------------
      # Quick start deployment

      - name: Setup quickstart
        run: ./setup

      - name: Start quickstart
        run: docker compose up -d

      - name: Healthcheck quickstart
        uses: stringbean/docker-healthcheck-action@v3
        with:
          container: breedbase
          wait-time: 600
          require-status: running
          require-healthy: true

      - name: Stop quickstart
        run: docker compose down

      - name: Clean production volumes
        run: docker volume prune -a

      - name: Clean data directory
        run: rm -rf data

      # -----------------------------------------------------------------------
      # Check development deployment

      - name: Setup development
        run: ./setup

      - name: Start development
        run: docker compose up -f docker-compose.development.yml up -d

      - name: Healthcheck development
        uses: stringbean/docker-healthcheck-action@v3
        with:
          container: breedbase
          wait-time: 600
          require-status: running
          require-healthy: true

      - name: Stop development
        run: docker compose down

      - name: Clean development volumes
        run: docker volume prune -a

      - name: Clean data directory
        run: rm -rf data

      # -----------------------------------------------------------------------
      # Testing

      # Patch database, and dump to file, build node modules
      - name: Load/dump fixture database and build node modules
        run: ./run_test --dumpupdatefixture t/unit/CXGN/String

      # Unit tests don't need a database or a server
      - name: Run unit tests
        run: ./run_test --nopatch --noserver t/unit 2>/dev/null

      # # Everything else needs a database and a server
      # - name: Run fixture tests
      #   run: |
      #     $RUN_TEST_CMD "--nopatch t/unit_fixture 2>/dev/null"
      #     $PRUNE_CMD

      # - name: Run mech tests
      #   run: |
      #     $RUN_TEST_CMD "--nopatch t/unit_mech 2>/dev/null"
      #     $PRUNE_CMD

      # # Run all selenium tests individually to avoid solgs for now
      # - name: Run selenium tests lists
      #   run: |
      #     $RUN_TEST_CMD "--nopatch t/selenium2/01_list 2>/dev/null"
      #     $PRUNE_CMD

      # - name: Run selenium tests trial
      #   run: |
      #     $RUN_TEST_CMD "--nopatch t/selenium2/02_trial 2>/dev/null"
      #     $PRUNE_CMD

      # - name: Run selenium tests dataset
      #   run: |
      #     $RUN_TEST_CMD "--nopatch t/selenium2/03_dataset 2>/dev/null"
      #     $PRUNE_CMD

      # - name: Run selenium tests breeders
      #   run: |
      #     $RUN_TEST_CMD "--nopatch t/selenium2/breeders 2>/dev/null"
      #     $PRUNE_CMD

      # - name: Run selenium tests onto
      #   run: |
      #     $RUN_TEST_CMD "--nopatch t/selenium2/onto 2>/dev/null"
      #     $PRUNE_CMD

      # - name: Run selenium tests search
      #   run: |
      #     $RUN_TEST_CMD "--nopatch t/selenium2/search 2>/dev/null"
      #     $PRUNE_CMD

      # - name: Run selenium tests stock
      #   run: |
      #     $RUN_TEST_CMD "--nopatch t/selenium2/stock 2>/dev/null"
      #     $PRUNE_CMD

      # - name: Run selenium tests tools
      #   run: |
      #     $RUN_TEST_CMD "--nopatch t/selenium2/tools 2>/dev/null"
      #     $PRUNE_CMD
