# Re-usable workflow to test treeimprovementbase site overlay
name: treeimprovementbase

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 0'

jobs:
  deployment:
    uses: ./.github/workflows/deployment.yml
    with:
      SITE_OVERLAY: treeimprovementbase

  test:
    uses: ./.github/workflows/test.yml
    with:
      SITE_OVERLAY: treeimprovementbase
